version: "3"
services:
  doh-proxy:
    image: jqtype/doh-proxy:jwt-auth
    container_name: doh-proxy-auth
    build:
      context: ./
    restart: unless-stopped
    env_file: .env
    ports:
      - 3000:3000/udp
      - 3000:3000/tcp
    volumes:
      - ./.env:/opt/doh-proxy/etc/.env
      - ${VALIDATION_KEY_PATH}:/opt/doh-proxy/etc/public_key.pem
      - ${DOMAIN_BLOCK_RULE}:/opt/doh-proxy/etc/block.txt
      - ${DOMAIN_OVERRIDE_RULE}:/opt/doh-proxy/etc/override.txt
      - ${LOG_FILE}:/var/log/doh-proxy/doh-proxy.log
    networks:
      net-front:

  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: watchtower
  #   command: dnscrypt-server --interval 30
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

networks:
  net-front:
    external: true
